version: '3.7'

services:
  mongo:
    image: mongo:4.4
    ports:
      - '27027:27017'
    volumes:
      - mongo-volume:/var/lib/mongo/data

  redis:
    image: redis:alpine
    ports:
      - '6389:6379'

volumes:
  mongo-volume:
    driver: local
